version: '3.7'

services:
  database_url_shortener:
    image: postgres
    container_name: database_url_shortener
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: url_shortener
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_url_shortener
    depends_on:
      - database_url_shortener

volumes:
  pgdata:
    driver: local